trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo build firstjob
    - bash: echo $(PipelineLevel)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildID)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/**.yml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
  - job: secondjob
    steps:
    - bash: echo build secondjob
#- stage: DevDeploy
#  variables:
#   environment: Dev
#  dependsOn: Build
#  jobs:
#  - job: Devdeploymentjob
#    steps:
#    - bash: echo $(environment)deploy firstjob
#- stage: QADeploy
#  variables:
#    environment: QA
#  dependsOn: Build
#  jobs:
#  - job: QADeployjob
#    steps:
#    - bash: echo $(environment)Deploy firstjob
#- stage: PRODDeploy
#  variables:
#   environment: PROD
#  dependsOn:
#  - DevDeploy
#  - QADeploy
#  jobs:
#  - job: PRDDeploy
#    steps:
#    - bash: echo $(environment)Deploy firstjob


